const writingPieces=[
{title:"Remember Me",category:"Poetry",excerpt:"A soft, aching poem about memory, girlhood, and wanting to be held in someone’s mind.",date:"July 7, 2026",readTime:"4 min read",featured:true,body:"Remember me gently. Remember me as a girl becoming language, as a prayer with shaky hands, as someone who loved with the whole room lit up inside her."},
{title:"Seeing in Color",category:"Essays",excerpt:"An essay about realizing the world is bigger, brighter, and more tender than survival mode allowed.",date:"July 3, 2026",readTime:"6 min read",featured:true,body:"For a long time, I mistook surviving for living. Then color returned slowly: in morning light, in laughter, in being honest about what hurt and what healed."},
{title:"Dear Friend",category:"Letters",excerpt:"A letter for the people we miss, forgive, outgrow, and still love in strange quiet ways.",date:"June 29, 2026",readTime:"5 min read",featured:true,body:"Dear friend, I hope you know I still carry the soft parts. Not the bitterness. Not the whole ache. Just the proof that we mattered once."},
{title:"A Prayer for Becoming",category:"Faith",excerpt:"A vulnerable faith reflection about returning to God while still feeling unfinished.",date:"June 20, 2026",readTime:"3 min read",body:"God, meet me in the middle of what I am still learning. Let me be soft without being weak, honest without being ashamed, and loved without performing."},
{title:"The Girl I Was",category:"Healing",excerpt:"A healing note about protecting your younger self while allowing your grown self to live.",date:"June 16, 2026",readTime:"4 min read",body:"The girl I was is not embarrassing. She was surviving with the tools she had. I honor her by choosing better without hating who she had to be."},
{title:"I Want Him",category:"Relationships",excerpt:"A dramatic, honest piece about love, longing, fear, devotion, and choosing yourself too.",date:"June 12, 2026",readTime:"5 min read",body:"Wanting someone can feel like worship if you are not careful. I am learning love can be deep without requiring me to disappear."},
{title:"The Pink Room",category:"Creative Writing",excerpt:"A glamorous short scene about a woman rebuilding her identity in a room that looks like rebellion.",date:"June 5, 2026",readTime:"7 min read",body:"The room was pink because she needed proof that softness could still take up space. Every wall said: begin again, but prettier this time."},
{title:"Soft but Not Small",category:"Poetry",excerpt:"A poem about feminine power, boundaries, tenderness, and being underestimated.",date:"May 28, 2026",readTime:"2 min read",body:"I am soft, but not small. Tender, but not yours to shape. I can bloom and still have boundaries."},
{title:"God Met Me There",category:"Faith",excerpt:"A reflection on feeling unworthy, returning to prayer, and finding grace in the middle.",date:"May 21, 2026",readTime:"4 min read",body:"Grace did not wait until I was clean. God met me there, in the unfinished place, with mercy I did not know how to ask for."}
];
const blogPosts=[
{title:"My Writing Process Lately",category:"Writing Process",excerpt:"How I turn messy notes, journal entries, and emotional spirals into finished pieces."},
{title:"Behind the Scenes of My Portfolio",category:"Behind the Scenes",excerpt:"The mood board, colors, fonts, and feelings behind this soft editorial writing space."},
{title:"Favorite Books for Becoming",category:"Favorite Books",excerpt:"Books that make me want to write, pray, romanticize my life, and tell the truth."}
];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let activeCategory="All";
function card(piece){return `<article class="writing-card fade-in" data-category="${piece.category}"><div class="thumb"></div><div class="writing-card-content"><span class="category">${piece.category}</span><h3 class="card-title">${piece.title}</h3><p class="card-excerpt">${piece.excerpt}</p><p class="card-excerpt">${piece.date} • ${piece.readTime}</p><a href="#post-template" class="read-more" data-title="${piece.title}">Read More →</a></div></article>`}
function renderFeatured(){const el=$("#featuredPieces");if(el)el.innerHTML=writingPieces.filter(p=>p.featured).map(card).join("")}
function renderLatest(){const el=$("#latestWriting");if(el)el.innerHTML=writingPieces.slice(3,6).map(p=>`<article class="latest-item fade-in"><div class="mini-thumb"></div><div><span class="category">${p.category}</span><h3>${p.title}</h3></div><small>${p.date}</small><small>${p.readTime}</small></article>`).join("")}
function renderPortfolio(){const grid=$("#portfolioGrid");const input=$("#searchInput");if(!grid)return;const q=(input?.value||"").toLowerCase();const filtered=writingPieces.filter(p=>(activeCategory==="All"||p.category===activeCategory)&&[p.title,p.category,p.excerpt].join(" ").toLowerCase().includes(q));grid.innerHTML=filtered.map(card).join("")||`<p>No pieces found.</p>`;observeFadeIns();attachReadMore()}
function renderBlog(){const el=$("#blogGrid");if(el)el.innerHTML=blogPosts.map(p=>`<article class="blog-card fade-in"><span class="category">${p.category}</span><h3>${p.title}</h3><p class="card-excerpt">${p.excerpt}</p><a href="#post-template" class="read-more" data-title="${p.title}">Read More →</a></article>`).join("")}
function attachReadMore(){$$(".read-more").forEach(a=>a.onclick=e=>{const title=e.currentTarget.dataset.title;const p=writingPieces.find(x=>x.title===title)||{title,category:"Journal",date:"2026",readTime:"3 min read",body:"This is a placeholder journal entry. Replace this with your full post when you are ready."};$("#postTitle").textContent=p.title;$("#postMeta").innerHTML=`<span>${p.date}</span><span>${p.category}</span><span>${p.readTime}</span>`;$("#postBody").textContent=p.body;})}
function observeFadeIns(){const obs=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add("visible");obs.unobserve(en.target)}}),{threshold:.12});$$(".fade-in").forEach(el=>obs.observe(el))}
$("#filterButtons")?.addEventListener("click",e=>{if(!e.target.matches(".filter-btn"))return;$$('.filter-btn').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');activeCategory=e.target.dataset.category;renderPortfolio()});$("#searchInput")?.addEventListener("input",renderPortfolio);$("#themeToggle")?.addEventListener("click",()=>{document.body.classList.toggle("dark");$("#themeToggle").textContent=document.body.classList.contains("dark")?"☀":"☾";localStorage.setItem("zoieTheme",document.body.classList.contains("dark")?"dark":"light")});$("#navToggle")?.addEventListener("click",()=>$("#navLinks").classList.toggle("open"));$$(".nav-links a").forEach(a=>a.onclick=()=>$("#navLinks").classList.remove("open"));window.addEventListener("scroll",()=>{const top=window.scrollY;const h=document.documentElement.scrollHeight-window.innerHeight;$("#scrollProgress").style.width=`${h>0?top/h*100:0}%`;$("#backToTop").classList.toggle("show",top>500)});$("#backToTop")?.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));$("#copyLink")?.addEventListener("click",async()=>{await navigator.clipboard?.writeText(location.href);$("#copyLink").textContent="Copied!";setTimeout(()=>$("#copyLink").textContent="Copy Link",1500)});document.querySelectorAll("form").forEach(f=>f.addEventListener("submit",e=>{e.preventDefault();alert("This form is a front-end placeholder. Connect it to Formspree, Netlify Forms, or another service when publishing.")}));
function init(){if(localStorage.getItem("zoieTheme")==="dark"){document.body.classList.add("dark");$("#themeToggle").textContent="☀"}renderFeatured();renderLatest();renderPortfolio();renderBlog();attachReadMore();observeFadeIns()}init();
